### ISSUE TITLE
Machine Configuration

### ISSUE THREAD

**Issue by 674177769** [wsdream/WS-DREAM#5]
What's the Machine Configuration when you run the program run_rt.py（WSPred）, I run this code and it's always tell me memory error

**Comment by jimzhu** [comment]
We use a Linux server for testing, which has 160G memory. If you run the code for 20 rounds in parallel, it will need about 40G memory due to the parallelization of tasks. So you would better to run 1 round instead.

**Comment by 674177769** [comment]
Thanks for your reply. Now I use a Linux server for running the program, for 20 rounds and 300 iteration in parallel. But it took about 5 days to finish. May I ask how long you run the program for 20 rounds and 300 iteration in parallel?
